# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b4098175255f848b93b6cb4bf6407f9f86adc493d8d12a1aea9eb89245c77ce5e29692a0ce87ca163ff6b2654eeba3ef53aa84cedc08ffc579a99cf1e6a7400

test:
  secret_key_base: 6b67ed953eb2796e200a64183b0eafd7581f120d350993c92fea80dd07536ce54454ee1451abbe19c2ee348d907b451146e40d17811e64b60f0aeb7d0783a7d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
